import { siteUrl } from '../components/siteConfig'

export const homeMetaDescription =
  'Armedia is a New Zealand marketing media agency in Auckland helping brands with strategy, advertising, Google Ads, Meta ads, SEO, digital media, OOH, AI workflows, BI dashboards, web design, and campaign reporting.'

export const homeKeywords = [
  'Armedia',
  'marketing media agency New Zealand',
  'marketing agency Auckland',
  'advertising agency Auckland',
  'advertising agency New Zealand',
  'digital marketing agency NZ',
  'digital media agency Auckland',
  'media planning agency New Zealand',
  'media planning agency Auckland',
  'AI marketing agency New Zealand',
  'AI marketing workflows Auckland',
  'business intelligence agency Auckland',
  'BI dashboards marketing NZ',
  'growth strategy agency Auckland',
  'brand strategy agency New Zealand',
  'campaign reporting agency',
  'performance marketing agency Auckland',
  'Google Ads agency Auckland',
  'Google Ads management New Zealand',
  'Meta ads agency Auckland',
  'Facebook ads agency NZ',
  'paid social advertising Auckland',
  'SEO agency Auckland',
  'SEO services New Zealand',
  'search engine optimisation Auckland',
  'web design agency Auckland',
  'website design New Zealand',
  'ecommerce marketing Auckland',
  'ecommerce website Auckland',
  'Next.js agency New Zealand',
  'React development NZ',
  'OOH advertising New Zealand',
  'outdoor advertising Auckland',
  'billboard advertising NZ',
  'offline marketing agency Auckland',
  'integrated marketing agency NZ',
  'full service marketing agency Auckland',
  'B2B marketing agency New Zealand',
  'SME marketing agency Auckland',
  'lead generation agency Auckland',
  'conversion marketing agency NZ',
  'content marketing agency Auckland',
  'social media marketing Auckland',
  'marketing consultancy New Zealand',
  'marketing automation agency NZ',
  'campaign management agency Auckland',
  'brand growth agency New Zealand',
  'Wellington marketing agency',
  'Christchurch marketing agency',
  'Remuera marketing agency',
  'Auckland growth marketing',
  'New Zealand advertising services',
  'marketing intelligence agency',
  'retail marketing agency Auckland',
  'healthcare marketing New Zealand',
  'construction marketing agency NZ',
  'SaaS marketing agency Auckland',
  'CRM marketing support NZ',
  'landing page agency Auckland',
  'marketing analytics agency',
]

export const homeServiceTypes = [
  'Marketing Strategy',
  'Brand Growth Strategy',
  'Advertising',
  'Google Ads Management',
  'Meta Advertising',
  'Digital Media',
  'SEO',
  'Web Design',
  'E-commerce Marketing',
  'Business Intelligence',
  'AI Marketing Workflows',
  'Media Planning',
  'Campaign Reporting',
  'OOH Media',
  'Offline Marketing',
  'Content Marketing',
  'Social Media Marketing',
  'Lead Generation',
  'Marketing Analytics',
]

export const homeSearchTopics = [
  { label: 'Marketing strategy Auckland', href: '/services#brand-growth-strategy' },
  { label: 'Google Ads management NZ', href: '/services#advertising' },
  { label: 'Meta advertising agency', href: '/services#advertising' },
  { label: 'SEO agency Auckland', href: '/seo-agency-auckland' },
  { label: 'Web design Auckland', href: '/web-design-auckland' },
  { label: 'E-commerce marketing', href: '/ecommerce-website-auckland' },
  { label: 'AI marketing workflows', href: '/services#ai-marketing-studio' },
  { label: 'BI dashboards & reporting', href: '/services#business-intelligence' },
  { label: 'Digital media planning', href: '/services#digital-media' },
  { label: 'OOH & offline media', href: '/services#ooh-offline-media' },
  { label: 'Next.js development NZ', href: '/nextjs-agency-new-zealand' },
  { label: 'React development Auckland', href: '/react-development-nz' },
  { label: 'Performance advertising', href: '/services#advertising' },
  { label: 'Campaign analytics', href: '/services#business-intelligence' },
  { label: 'Brand positioning', href: '/services#brand-growth-strategy' },
  { label: 'Lead generation campaigns', href: '/contact' },
  { label: 'Marketing agency Wellington', href: '/contact' },
  { label: 'Marketing agency Christchurch', href: '/contact' },
  { label: 'Full-service media agency', href: '/services' },
  { label: 'Growth consultation', href: '/start-project' },
]

export function buildHomeStructuredData(faqSchemaItems: Array<{ question: string; answer: string }>) {
  return [
    {
      '@context': 'https://schema.org',
      '@type': 'WebPage',
      '@id': `${siteUrl}/#webpage`,
      url: siteUrl,
      name: 'Armedia | Marketing Media Agency Auckland & New Zealand',
      description: homeMetaDescription,
      inLanguage: 'en-NZ',
      isPartOf: { '@id': `${siteUrl}/#website` },
      about: { '@id': `${siteUrl}/#localbusiness` },
      keywords: homeKeywords.slice(0, 40).join(', '),
    },
    {
      '@context': 'https://schema.org',
      '@type': 'ProfessionalService',
      '@id': `${siteUrl}/#professional-service`,
      name: 'Armedia Marketing Media Agency',
      url: siteUrl,
      image: `${siteUrl}/logo.png`,
      description: homeMetaDescription,
      areaServed: ['Auckland', 'Wellington', 'Christchurch', 'New Zealand', 'Australia'],
      serviceType: homeServiceTypes,
      knowsAbout: [
        'Marketing Strategy',
        'Digital Advertising',
        'Search Engine Optimisation',
        'Social Media Advertising',
        'Marketing Analytics',
        'Artificial Intelligence in Marketing',
        'Business Intelligence Dashboards',
        'Outdoor Advertising',
        'Web Development',
        'E-commerce Growth',
      ],
      hasOfferCatalog: {
        '@type': 'OfferCatalog',
        name: 'Marketing & Media Services',
        itemListElement: homeServiceTypes.map((service) => ({
          '@type': 'Offer',
          itemOffered: {
            '@type': 'Service',
            name: service,
          },
        })),
      },
    },
    {
      '@context': 'https://schema.org',
      '@type': 'FAQPage',
      mainEntity: faqSchemaItems.map((item) => ({
        '@type': 'Question',
        name: item.question,
        acceptedAnswer: {
          '@type': 'Answer',
          text: item.answer,
        },
      })),
    },
  ]
}
